### PR TITLE
Update user agent to fix issue with some Matomo installs

### LINKED ISSUE #5444: Problem logging in via iPhone
Having the very last Matomo version installed

CleanShot 2023-01-25 at 21 51 37@2x

The System summary is

CleanShot 2023-01-25 at 21 51 18@2x

I am not able to log in via my iPhone.

CleanShot 2023-01-25 at 21 52 23@2x

Having the following message

CleanShot 2023-01-25 at 21 52 44@2x

When logging in via website with same url, user and password

CleanShot 2023-01-25 at 21 53 24@2x

I am perfectly able to access

CleanShot 2023-01-25 at 21 53 42@2x

I was able to see my information via my iPhone till few weeks ago when sudently I started having that error.

### PR DESCRIPTION
**Pull request by tsteur**
refs #5444 

The old user agent was blocked by some web servers.

Also improving getting token as most users should use Matomo 4 these days. Not relevant for the actual change.

This also updates the titanium SDK

### CODE REVIEW

**Comment by tsteur** [comment]
Found the problem for the crash that is happening (unrelated to the user's issue). Some translations contain `%1$s` etc and String.format fails on this and crashes the app.

**Comment by tsteur** [comment]
Tested it and all works now

**Comment by m1ga** [comment]
you should update the store version too. That one is still from Apr 2022

**Comment by tsteur** [comment]
Thanks @m1ga  the store version is the version in the tiapp.xml? I've updated it locally already. Been trying to troubleshoot for hours why it would show left menu like this 
image

and when I set `extendSafeArea:true` then it fills out the space of the left menu nicely but the labels are still not positioned to the left.

**Comment by m1ga** [comment]
This is how the current master looks on my phone (Pixel 7, Android 13):

Screenshot_20230315-201100

Screenshot_20230315-201046

the white bar in the landscape image is because of the cutout camera on that side.


For a store update you increase: https://github.com/matomo-org/matomo-mobile-2/blob/master/tiapp.xml#L10 and the both numbers in https://github.com/matomo-org/matomo-mobile-2/blob/master/tiapp.xml#L56
Then build the apk and upload it

**Comment by tsteur** [comment]
That issue I actually only have on iOS. Thanks for mentioning this.

**Comment by m1ga** [comment]
ah ok :smile: can't test that at the moment, sorry

**Pull request merged**
