### PR TITLE
global app update

### PR DESCRIPTION
**Pull request by m1ga**
First: awesome to see your app is build with Titanium and still maintained :rocket: 

I've updated it to the latest SDK, Material UI and made other changes:

* fixed some getter/setter errors
* moved to Adaptive Icons
* fixed row heights
* added Titanium installation infos to the readme
* cleaned some images that produced merging errors while building the app
* removed the mobileweb parts (less code :wink: )

only tested it with the Android version and a demo account! If there are any errors please report them and I'll check them again.

Note: I didn't change the version number

### CODE REVIEW

**Comment by tsteur** [comment]
Thanks for this @m1ga . Really appreciated. I just wanted to give it a test but can't download the latest 11.1 via `ti sdk`. It's still trying to download it from appcelerator. Do you have any idea how this works since they removed support for it?

**Comment by m1ga** [comment]
Hi @tsteur . You are still using the old CLI: `ti -v` should be 6.1.1. Run `sudo npm i -g titanium alloy` to get the latest. Then it will download from Github

**Comment by Findus23** [comment]
Do I understand https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_Getting_Started/Prerequisites/Installing_Oracle_JDK.html correctly that one can now also use Titanium with OpenJDK?

So it is finally possible to build this app using only Free Software?
In that case I could finally continue https://github.com/matomo-org/matomo-mobile-2/issues/5274#issuecomment-414038344 and at least get a CI running that builds the Android app on every commit.

**Comment by m1ga** [comment]
@Findus23 yes, I'm using OpenJDK for quiet a while now (2 years?). You can use this github action https://github.com/marketplace/actions/titanium-android-build to build it like this https://github.com/m1ga/ti.githubAction/blob/main/.github/workflows/main.yml

**Comment by tsteur** [comment]
Sorry for getting back to you so late @m1ga  and thanks @m1ga I can now download the latest version and build the app 👍  I've tested it and all looks good 👍  Thanks for this

**Pull request merged**
